# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Utils
                                 A QGIS plugin
 Computes ecological continuities based on environments permeability
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-04-12
        git sha              : $Format:%H$
        copyright            : (C) 2018 by IRSTEA
        email                : mathieu.chailloux@irstea.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

"""
    Utility functions independent from QGIS API.
"""

import datetime
import os.path
import pathlib
import sys
import platform

file_dir = os.path.dirname(__file__)
if file_dir not in sys.path:
    sys.path.append(file_dir)

# LOG UTILITIES

def printLine(msg):
    print(msg + "\n")

debug_flag=True
print_func = printLine
curr_language = "fr"
dialog_base_dir = None

platform_sys = platform.system()


class CustomException(Exception):
    def __init__(self, message):
        super().__init__(message)
class UserError(Exception):
    def __init__(self, message):
        super().__init__(message)
class InternalError(Exception):
    def __init__(self, message):
        super().__init__(message)
class TodoError(Exception):
    def __init__(self, message):
        super().__init__(message)


def printDate(msg):
    date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print_func ("[" + date_str + "] " + msg)

def debug(msg):
    if debug_flag:
        printDate("<font color=\"gray\">[debug] " + msg + "</font>")

def info(msg):
    printDate("<font color=\"black\">[info] " + msg + "</font>")

def warn(msg):
    printDate("<font color=\"orange\">[warn] " + msg + "</font>")

def mkBoldRed(msg):
    return "<b><font color=\"red\">" + msg + "</font></b>"

def error_msg(msg,prefix=""):
    printDate(mkBoldRed("[" + prefix + "] " + msg))

def user_error(msg):
    raise UserError(msg)

def internal_error(msg):
    raise InternalError(msg)

# def todo_error(msg):
#     raise TodoError(msg)


# FILE UTILITIES

def normPath(fname):
    p = pathlib.Path(fname)
    pp = p.as_posix()
    return pp
    #return fname.replace('\\','/')

def joinPath(p1,p2):
    pp1 = pathlib.Path(p1)
    res = pp1.joinpath(p2)
    return res.as_posix()

def mkDir(dirname):
    if not os.path.isdir(dirname):
        info("Creating directory '" + dirname + "'")
        os.makedirs(dirname)
    return dirname

def createSubdir(par_dir,name):
    path = joinPath(par_dir,name)
    return mkDir(path)

def pathEquals(p1,p2):
    if p1 and p2:
        p1_parts = pathlib.Path(p1).parts
        p2_parts = pathlib.Path(p2).parts
        return (p1_parts == p2_parts)
    else:
        return False
     
def fileExists(fname,prefix=""):
    if not fname:
        return False
    path = pathlib.Path(fname)
    if not path.exists():
        return False
    if not (os.path.isfile(fname)):
        return False
    return True

def checkFileExists(fname,prefix=""):
    path = pathlib.Path(fname)
    debug("path = " + str(path))
    debug("pathparts = " + str(path.parts))
    if not path.exists():
        user_error("path does not exist : " + str(path))
    if not fname:
        user_error(prefix + " File not selected")
    if not (os.path.isfile(fname)):
        user_error(prefix + "File '" + fname + "' does not exist")
        
def removeFile(path):
    if os.path.isfile(path):
        debug("Deleting existing file '" + path + "'")
        os.remove(path)

def writeFile(fname,str):
    with open(fname,"w",encoding="utf-8") as f:
        f.write(str)

# PATH UTILITIES

def mkTmpPath(path,suffix="_tmp"):
    bn,extension = os.path.splitext(path)
    return (bn + suffix + extension)

        