# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LightPollutionAbout_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt.QtCore import (
    QCoreApplication,
    QMetaObject,
    QRect,
    QSize
)
from qgis.PyQt.QtGui import (
    QPixmap
)
from qgis.PyQt.QtWidgets import (
    QFrame,
    QLabel,
    QSizePolicy,
    QVBoxLayout
)
from .qgis_lib.qt_compatibility import (
    SIZEPOLICY_PREFERRED,
    SIZEPOLICY_EXPANDING,
    SIZEPOLICY_FIXED,
    SIZEPOLICY_MINIMUM_EXPANDING,
    FRAME_NO_FRAME,
    FRAME_RAISED
)

class Ui_LightPollutionAbout(object):
    def setupUi(self, LightPollutionAbout):
        LightPollutionAbout.setObjectName("LightPollutionAbout")
        LightPollutionAbout.resize(888, 391)
        sizePolicy = QSizePolicy(SIZEPOLICY_PREFERRED, SIZEPOLICY_PREFERRED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LightPollutionAbout.sizePolicy().hasHeightForWidth())
        LightPollutionAbout.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(LightPollutionAbout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QFrame(LightPollutionAbout)
        sizePolicy = QSizePolicy(SIZEPOLICY_EXPANDING, SIZEPOLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(80)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(0, 90))
        self.frame.setFrameShape(FRAME_NO_FRAME)
        self.frame.setFrameShadow(FRAME_RAISED)
        self.frame.setObjectName("frame")
        self.label_2 = QLabel(self.frame)
        self.label_2.setGeometry(QRect(80, 30, 102, 25))
        sizePolicy = QSizePolicy(SIZEPOLICY_FIXED, SIZEPOLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QSize(102, 25))
        self.label_2.setText("")
        self.label_2.setPixmap(QPixmap(":/plugins/LightPollutionToolbox/icons/logoINRAE.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QLabel(self.frame)
        self.label_3.setGeometry(QRect(320, 10, 136, 68))
        sizePolicy = QSizePolicy(SIZEPOLICY_FIXED, SIZEPOLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QSize(136, 68))
        self.label_3.setText("")
        self.label_3.setPixmap(QPixmap(":/plugins/LightPollutionToolbox/icons/logoTetis.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QLabel(self.frame)
        self.label_4.setGeometry(QRect(700, 20, 111, 50))
        self.label_4.setText("")
        self.label_4.setPixmap(QPixmap(":/plugins/LightPollutionToolbox/icons/logoOccitanie.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QLabel(self.frame)
        self.label_5.setGeometry(QRect(550, 10, 53, 68))
        sizePolicy = QSizePolicy(SIZEPOLICY_FIXED, SIZEPOLICY_FIXED)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QSize(53, 68))
        self.label_5.setText("")
        self.label_5.setPixmap(QPixmap(":/plugins/LightPollutionToolbox/icons/logoMTES.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.frame)
        self.label = QLabel(LightPollutionAbout)
        sizePolicy = QSizePolicy(SIZEPOLICY_MINIMUM_EXPANDING, SIZEPOLICY_MINIMUM_EXPANDING)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(LightPollutionAbout)
        QMetaObject.connectSlotsByName(LightPollutionAbout)

    def retranslateUi(self, LightPollutionAbout):
        _translate = QCoreApplication.translate
        LightPollutionAbout.setWindowTitle(_translate("LightPollutionAbout", "LightPollutionToolBox - About"))
        self.label.setText(_translate("LightPollutionAbout", "<html><head/><body><p>LightPollutionToolBox is a QGIS 3 plugin (GNU GPLv3 licence) allowing the generation of light pollution indicators from satellite images.</p><p>The plugin has been developped by research unit UMR TETIS at INRAE in 2023. </p><p>This project has been funded by Occitanie Region, and developed through a partnership with La Telescop.</p><p><span style=\" font-style:italic;\">Designer / Developper </span>: Antoine Sensier (antoine.sensier@inrae.fr)</p><p><span style=\" font-style:italic;\">Project initiator</span> : Jennifer Amsallem (jennifer.amsallem@inrae.fr)</p><p><span style=\" font-style:italic;\">Links:</span> :</p><p>- LightPollutionToolBox GitHub: <a href=\"https://github.com/MathieuChailloux/BioDispersal\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/MathieuChailloux/LightPollutionToolbox</span></a></p><p>- LightPollutionToolBox bugtracker: <a href=\"https://github.com/MathieuChailloux/BioDispersal/issues\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/MathieuChailloux</span></a><a href=\"https://github.com/MathieuChailloux/BioDispersal\"><span style=\" text-decoration: underline; color:#0000ff;\">/LightPollutionToolbox</span></a><a href=\"https://github.com/MathieuChailloux/BioDispersal/issues\"><span style=\" text-decoration: underline; color:#0000ff;\">l/issues</span></a></p><p>- UMR TETIS: <a href=\"https://tetis.teledetection.fr\"><span style=\" text-decoration: underline; color:#0000ff;\">https://tetis.teledetection.fr</span></a></p><p>- INRAE: <a href=\"https://www.inrae.fr/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.inrae.fr/</span></a></p></body></html>"))
